export const LOADING_USER = "LOADING_USER";
export const LOADING_USER_SUCCESSFUL = "LOADING_USER_SUCCESSFUL";
export const LOGOUT_USER_SUCCESSFUL = "LOGOUT_USER_SUCCESSFUL";
export const UPDATE_USER_SUCCESSFUL = "UPDATE_USER_SUCCESSFUL";
export const LOADING_POSTS_SUCCESSFUL = "LOADING_POSTS_SUCCESSFUL";
export const CREATING_POSTS_SUCCESSFUL = "CREATING_POSTS_SUCCESSFUL"
export const DELETE_POSTS_SUCCESSFUL = "DELETE_POSTS_SUCCESSFUL";
export const EDIT_POSTS_SUCCESSFUL = "EDIT_POSTS_SUCCESSFUL";
